# image_root: '/export/share/datasets/vision/coco/images/'
image_root: '/home/newdisk/zxy/pj3/coco/images/'
# ann_root: 'annotation'
ann_root: '/home/newdisk/zxy/pj3/coco/annotations/annotations_clean'
ann_root_DCC: '/home/newdisk/zxy/pj3/coco/annotations/annotations_DCC'
# coco_gt_root: 'annotation/coco_gt'
coco_gt_root: '/home/newdisk/zxy/pj3/coco/annotations/annotations_clean'

# set pretrained as a file path or an url
best: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'
# checkpoint: '/home/newdisk/zxy/pj3/coco/BLIP-main/output/Caption_coco_best/checkpoint_best.pth'
checkpoint: '/home/newdisk/zxy/pj3/coco/BLIP-main/output/Caption_coco_pretrained/checkpoint_best.pth'
# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 6
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10

